# https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
- name: Update apt cache
  apt:
    update_cache: true
    # Enabling the following line will upgrade the kernel
    #upgrade: dist
    clean: true
  register: update_result

- debug:
    msg: "Update results are {{update_result}}"

- name: Check if a reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot required
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Install common system packages
  apt:
    name: "{{ item }}"
  with_items:
    - zsh
    - vim

- name: Set default shell for current user
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- user:
    name: "{{ ansible_user }}"
  register: current_user

- name: Find Oh-My-Zsh Install Folder
  stat:
    path: "{{current_user.home}}/.oh-my-zsh"
  register: omzsh_dir

- block:
  - tempfile:
      state: directory
    register: temp_dir

  - name: Download Oh-My-Zsh installer
    get_url:
      url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "{{temp_dir.path}}"

  - stat:
      path: "{{current_user.home}}/.zshrc"
    register: original_zshrc

  - name: Installing Oh-My-Zsh
    shell: "/bin/sh {{temp_dir.path}}/install.sh --unattended --keep-zshrc"

 # If there was no zshrc file when we started, oh-my-zsh will generate one for
 # us, even with the keep-zshrc flag, so we purge that useless file here
  - file:
      path: "{{current_user.home}}/.zshrc"
      state: absent
    when: not original_zshrc.stat.exists

  when: not omzsh_dir.stat.exists
  become: yes
  become_user: "{{current_user.name}}"

- name: Update .zshrc file for Oh-My-Zsh
  blockinfile:
    path: "{{ current_user.home }}/.zshrc"
    marker: "{mark} Oh-My-Zsh"
    marker_begin: "{{BLOCK_START_MARKER}}"
    marker_end: "{{BLOCK_END_MARKER}}"
    create: true
    block: |
      export ZSH="$HOME/.oh-my-zsh"
      ZSH_THEME="{{omzsh_theme}}"
      plugins=(
        {{ omzsh_plugins }}
      )

      # Case Sensitive Auto-Complete
      CASE_SENSITIVE="true"

      # Disable marking of untraced files in Git folders as "dirty"
      # Improves performance on large repos significantly
      DISABLE_UNTRACKED_FILES_DIRTY="true"

      source $ZSH/oh-my-zsh.sh
  become: yes
  become_user: "{{current_user.name}}"