- name: Update apt cache
  apt:
    update_cache: true

- name: Install common system packages
  apt:
    name: "{{ item }}"
  with_items:
    - zsh
    - vim

- name: Set default shell for current user
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh


# TODO: deploy dotfiles for kevin user
# TODO: change kevin user to use a more secure password, or create a local
#       admin account and remove kevin user from sudoers