---
- hosts: homeserver2
  roles:
    - role: shell
    - role: git
    - role: dotfiles
    - role: docker
    - role: homeassistant
    - role: unifi

- hosts: homeserver1
  roles:
    - role: minecraft