- block:
  - name: See if dotfiles are already installed
    set_fact:
      DOT_FILES_DIR: "~/.dotfiles"

  - stat:
      path: "{{ DOT_FILES_DIR }}"
    register: dot_files_dir

- name: Checkout dotfiles project
  git:
    repo: "git@github.com:TheFriendlyCoder/dotfiles.git"
    dest: "{{ DOT_FILES_DIR }}"
  when: not dot_files_dir.stat.exists

- name: symlink vim config file
  file:
    src: "~/.dotfiles/vim/.vimrc"
    dest: "~/.vimrc"
    state: link