- user:
    name: "{{ ansible_user }}"
  register: current_user

- name: Set user permissions
  template:
    src: permissions.json.j2
    dest: "{{current_user.home}}/minecraftbe/phillips_oasis/permissions.json"
    group: "{{ current_user.group }}"
    owner: "{{ current_user.uid }}"
    backup: true
    mode: 0644
  notify: "Restart Minecraft Service"

- name: Create backup script
  copy:
    src: upload.sh
    dest: "~/minecraftbe/phillips_oasis/upload.sh"
    mode: 0700

# TODO: add backup config, maybe with a new onedrive role
# TODO: rework backup logic to use separate cron that doesn't rely on update script (will make service reboots faster)
# TODO: add logic to deploy and setup Minecraft (pull out custom scripts into Ansible)
# TODO: create custom role for BIND setup