- tempfile:
    state: directory
  register: temp_dir

- name: Download installer
  get_url:
    url: https://dl.ui.com/unifi/7.3.76/unifi_sysvinit_all.deb
    dest: "{{temp_dir.path}}"
  register: installer

- debug:
    msg: "Result is {{installer}}"

# TODO: install
# https://community.ui.com/questions/UniFi-Installation-Scripts-or-UniFi-Easy-Update-Script-or-UniFi-Lets-Encrypt-or-UniFi-Easy-Encrypt-/ccbc7530-dd61-40a7-82ec-22b17f027776