- name: Add Docker apt repository key.
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt cache
  apt:
    update_cache: true

- name: Install latest Docker version
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

- name: create Docker group
  group:
    name: docker

- name: add local users to Docker group
  user:
    name: "{{ item }}"
    append: true
    groups:
    - docker
  with_items:
    - kevin
